services:
  - type: web
    name: bitespeed-identity-reconciliation-megha
    env: node
    plan: free
    buildCommand: |
      npm install --include=dev
      npm run db:generate
      npm run build
    startCommand: |
      npx prisma generate
      npx prisma migrate deploy
      npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: bitespeed-db
          property: connectionString
    autoDeploy: false

databases:
  - name: bitespeed-db
    databaseName: bitespeed_identity
    user: bitespeed_user
    plan: free