services:
  - type: web
    name: bitespeed-identity-reconciliation-megha
    env: node
    plan: free
    buildCommand: npm install --include=dev && npm run build && npm run db:generate
    startCommand: npm run db:migrate && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: bitespeed-db
          property: connectionString
    autoDeploy: false

databases:
  - name: bitespeed-db
    databaseName: bitespeed_identity
    user: bitespeed_user
    plan: free